website/routes/web.php
        Route::resource('profile', 'Admin\ProfileController');
        
        #Admin password change
        Route::get('password/change', array('uses' => 'Admin\ProfileController@changePassword', 'as' => 'admin.password.change'));
        Route::post('password/change', array('uses' => 'Admin\ProfileController@updatePassword', 'as' => 'admin.password.change'));
        
        #Services Management
        Route::get('services/ServicesData', 'Admin\ServicesController@getServicesData');
        Route::post('services/changeStatus', 'Admin\ServicesController@changeServiceStatus');
        Route::resource('services','Admin\ServicesController');
        
        Route::post('servicesCategory/changeStatus', 'Admin\ServiceCategoryController@changeServiceStatus');
        Route::get('listCategory', 'Admin\ServiceCategoryController@index')->name('listCategory');
        Route::get('addCategory', 'Admin\ServiceCategoryController@create')->name('addCategory');
        Route::post('saveCategory', 'Admin\ServiceCategoryController@saveCategory')->name('saveCategory');
        Route::get('editCategory/{id}', 'Admin\ServiceCategoryController@editCategory')->name('editCategory');
        Route::post('updateCategory', 'Admin\ServiceCategoryController@updateCategory')->name('updateCategory');
        Route::get('deleteCategory/{id}', 'Admin\ServiceCategoryController@deleteCategory')->name('deleteCategory');
        
        //Route::resource('services','Admin\ServiceCategoryController');
        
        
        #Booking Management
        Route::get('booking/export', 'Admin\BookingController@export');
        Route::any('booking/search', array('uses' => 'Admin\BookingController@search', 'as' => 'admin.booking.search'));
        Route::post('booking/changeStatus', 'Admin\BookingController@changeBookingStatus');
        
        /////////////////////////////////////////////////////////////////////
        Route::resource('appointments','Admin\BookingController');
        


        #Transaction Management
        Route::get('transaction/export', 'Admin\TransactionController@export');
        Route::any('transaction/search', array('uses' => 'Admin\TransactionController@search', 'as' => 'admin.transaction.search'));
        Route::resource('transaction','Admin\TransactionController');
        
        #User Management
        Route::post('users/updateCredit', 'Admin\UserController@updateCredit');
        Route::get('users/UserData', 'Admin\UserController@getUserData');
        Route::get('vendors/VendorData', 'Admin\VendorController@getVendorData');
        ///

        /////////////////////////////////////////////////////////////////////
        Route::get('bookings/BookingData', 'Admin\BookingController@getBookingData');



        Route::post('users/changeStatus', 'Admin\UserController@changeUserStatus');
        Route::get('users/show/{id}', 'Admin\UserController@show');
        Route::get('users/showuser/{id}', 'Admin\UserController@showuser');
        Route::resource('patients', 'Admin\UserController');
         Route::any('patient/Add', 'Admin\UserController@Add');
          Route::any('patient/addUser', 'Admin\UserController@AddUser');
           Route::any('patient/edit/{id}', 'Admin\UserController@edit');
            Route::any('patient/update/{id}', 'Admin\UserController@update');
         
         
        Route::resource('doctors', 'Admin\VendorController');
        // Route::any('deleteEdu','Admin\VendorController@deleteEdu')->name('deleteEdu');
        Route::get('vendors/show_vendor/{id}', 'Admin\VendorController@show_vendor');
        Route::post('vendor/reject', 'Admin\VendorController@rejectVendor');
        Route::post('venderService/changeStatus', 'Admin\VendorController@changeVenderServiceStatus');
        Route::post('venderService/addVenderService', 'Admin\VendorController@addVenderService');
        Route::post('venderService/delete', 'VenderServiceController@destroy');
        Route::post('vendorSlots/delete', 'Admin\VendorController@deleteVendorSlot');
       // Route::any('test-mail', 'Admin\VendorController@testMail')->name('test-mail');
         Route::any('test-mail', 'Admin\NotificationController@NotificationEmail')->name('test-mail');
        
          
          
        Route::resource('users.booking', 'Admin\BookingController');
        Route::resource('users.transaction', 'Admin\TransactionController');
        
        #chat Management
        Route::get('chatboard/history/{id}', 'Admin\ChatController@history');
        Route::get('chatboard/{id}', 'Admin\ChatController@index');
        Route::post('chatboard/store', 'Admin\ChatController@store');
        Route::post('chatboard/notificationCount', 'Admin\ChatController@getNotificationCount');
        Route::resource('chatboard', 'Admin\ChatController');
        
        #Enquiry Management
        Route::get('enquiry/EnquiryData', 'Admin\EnquiryController@getEnquiryData');
        Route::post('enquiry/changeStatus', 'Admin\EnquiryController@changeEnquiryStatus');
        Route::resource('enquiry','Admin\EnquiryController');

        #Notifications Management
        Route::get('notifications/{type}', 'Admin\NotificationController@getNotifications');
        
        Route::get('slots/SlotData', 'Admin\SlotController@getSlotData');
        Route::resource('slots','Admin\SlotController');
        Route::post('slots/update', 'Admin\SlotController@update');
        Route::post('slots/checkOverlappingSlots', 'Admin\SlotController@checkOverlappingSlots');

        #Vender Services
        Route::get('editVenderService/{id}', 'VenderServiceController@edit')->name('editVenderService');
        Route::get('editVender/{id}', 'Admin\VendorController@edit')->name('editVender');
        Route::any('updateVenderService/{id}', 'VenderServiceController@update')->name('updateVenderService');
        
        #Coupons
        Route::get('coupons/couponData', 'Admin\CouponController@getCouponData');
        Route::post('coupons/changeStatus', 'Admin\CouponController@changeCouponStatus');
        Route::resource('coupons','Admin\CouponController');
        
        #Banners
        Route::get('banners/bannerData', 'Admin\BannerController@getBannerData');
        Route::post('banners/changeStatus', 'Admin\BannerController@changeBannerStatus');
        Route::resource('banners', 'Admin\BannerController');

        #notification
        Route::any('notification/doctors', 'Admin\NotificationController@getVendorData');       

        
        #Refund
        Route::get('refund','Admin\BookingController@refund');
        Route::get('refundData','Admin\BookingController@refundData');
        Route::post('refund','Admin\BookingController@refundStripe');

        #faq
        Route::get('faq','Admin\SettingsController@faq');
        
         #faq
         Route::get('faq','Admin\SettingsController@faq');
         Route::get('faqData','Admin\SettingsController@faqData');
         Route::get('faq/{id}/edit','Admin\SettingsController@faqEdit');
         Route::post('faq/save-edit/{id}','Admin\SettingsController@faqSaveEdit');
         Route::get('faq/add','Admin\SettingsController@faqAdd');
         Route::post('faq/save-add','Admin\SettingsController@faqSaveAdd');
         Route::delete('faq/{id}','Admin\SettingsController@faqDelete');
         Route::any('deleteEdu','Admin\VendorController@deleteEdu');
    });
});


/** ------------------------------------------
 *  Doctor Routes
 *  ------------------------------------------
 */

Route::group(array('prefix' => 'doctor'), function() {
    
    Route::get('/', array('middleware' => 'guest.doctor', 'uses' => 'doctor\LoginController@getIndex'));
    Route::get('logout', array('uses' => 'doctor\LoginController@doLogout'));
    Route::post('login', array('uses' => 'doctor\LoginController@doLogin'));        
    // Password Reset Routes...
    Route::get('password/reset', array('uses'=>'doctor\ForgotPasswordController@showLinkRequestForm', 'as'=>'doctor.password.email'));
    Route::any('password/email', array('uses'=>'doctor\ForgotPasswordController@sendResetLinkEmail'));
    Route::get('password/update-form', array('uses'=>'doctor\UpdatePasswordController@update'));
    Route::post('password/update', array('uses'=>'doctor\UpdatePasswordController@updatePassword'));


    //after login
    Route::group(array('middleware' => 'auth.doctor'), function() {
        
        Route::get('dashboard/{currency}', 'doctor\DashboardController@index');
        
        // Appointments of a doctor in doctor panel
        Route::get('appointments','doctor\BookingController@index');
        Route::get('bookings/sendCallNoti','doctor\BookingController@sendCallNotification');
        Route::get('chat/{id}','doctor\ChatController@index')->name('doctorchat');
        Route::get('report/{id}','doctor\ReportController@index');
        Route::post('reports/save','doctor\ReportController@generate');
        Route::resource('patients', 'doctor\userController');
        
        /*--slots Routes--*/
        Route::post('slots/getslots','doctor\SlotController@getSlots');
        Route::any('slots/deletebreak','doctor\SlotController@deleteBreak');
        Route::get('slots/getslotsdata','doctor\SlotController@getSlotsData');
        Route::post('slots/save-date-breaks','doctor\SlotController@SaveDateBreaks');
        Route::get('slots/datebreak','doctor\SlotController@dateBreak');
        Route::post('slots/checkOverlappingSlots', 'doctor\SlotController@checkOverlappingSlots');
        Route::post('slots/insertVenderBreak', 'doctor\SlotController@insertVenderBreak');
	  
        Route::post('slots/update','doctor\SlotController@update');
        Route::get('bookings/BookingData', 'doctor\BookingController@getBookingData');
        Route::resource('slots','doctor\SlotController');
        Route::get('report/view/{id}','doctor\ReportController@view');
        Route::get('report/edit/{id}','doctor\ReportController@edit');

website/app/Http/Controllers/doctor/BookingController.php
<?php

namespace App\Http\Controllers\doctor;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Booking;
use App\BookingDetail;
use App\Service;
use App\Helpers\Datatable\SSP;
use App\DeviceDetails;

class BookingController extends Controller
{

    /**
     * Booking Model
     * @var Booking
     */
    protected $booking;
    protected $pageLimit;
    
    /**
     * Inject the models.
     * @param Booking $booking
     */
    public function __construct(Booking $booking) {
        $this->booking = $booking;
        $this->pageLimit = config('settings.pageLimit');

    }


    /**
     * Function to get all appointments of doctor
     * @param
     * @return View
     * @author Durga Parshad
     * @since 19-December-2019
     */
    public function index(){

        // Show the booking
        return view('doctor/bookingList');
    }


    public function getBookingData() {

        $userId = auth()->guard('doctor')->user()->id;
        $table = 'bookings';
        $primaryKey = 'id';    

        $columns = array(
            array('db' => 'bookings.reference_id', 'dt' => 0, 'field' => 'reference_id'), 
            array('db' => 'bookings.user_id', 'dt' => 10, 'field' => 'user_id'), 
            array('db' => 'pu.email', 'dt' => 1, 'field' => 'email'),
            array('db' => 'sc.cat_name', 'dt' => 2, 'field' => 'cat_name'),
            array('db' => 'pu.gender', 'dt' => 3, 'field' => 'gender'),
            array('db' => 'bookings.booking_date', 'dt' => 4, 'field' => 'booking_date'),
            array('db' => 'vs.start_time', 'dt' => 5, 'field' => 'start_time'),
            array('db' => "CONCAT(tr.currency, ' ', bookings.price )", "as" => "amount", 'dt' => 6, 'field' => 'amount'),
            array('db' => 'bookings.status', 'dt' => 7, 'field' => 'status', 'formatter' => function($d,$row){
                if($row['status'] == 1){
                    return '<span class="label label-warning">'.trans('doctor/booking.active').'</span>';
                }
                elseif($row['status'] == 2){
                    return '<span class="label label-danger">'.trans('doctor/booking.cancel').'</span>';
                }else{
                    return '<span class="label label-success">'.trans('doctor/booking.complete').'</span>';
                }
            }),
            array('db' => 'bookings.created_at', 'dt' => 8, 'field' => 'created_at'),
            array('db' => 'bookings.id', 'dt' => 9, 'formatter' => function( $d, $row ){
                // creating dynamically generated link where durl ---> dynamic url

                $durl  = env('CHAT_URL','default_value'); // fetched root part of link from env file
				$durl .="/room/".auth()->guard('doctor')->user()->id.$row['user_id']."/".
						auth()->guard('doctor')->user()->firstname;
                // $durl .= '/demos/dashboard/canvas-designer.html?open=true&sessionid=';
                // $durl  = $durl . auth()->guard('doctor')->user()->id .$row['user_id'];
                // $durl .= '&publicRoomIdentifier=dashboard&userFullName='. auth()->guard('doctor')->user()->firstname;
                // $durl .= '&sender_id='. auth()->guard('doctor')->user()->id;
                // $durl .= '&receiver_id='.$row['user_id'];
                // $durl .= '&audioconfig=true&videoconfig=true';

					
                if($row['status'] == 1){
                    $operation = ' <a href="report/' . $d .'" class="btn btn-primary d-inline-block" title="' . trans('doctor/report.generate') . '" data-toggle="tooltip"><i class="fa fa-file-pdf-o"></i></a>';
                    // call button
                    $operation .= ' <a href=" ' . $durl .'" class="btn btn-warning d-inline-block callIniat" title="' . trans('doctor/report.call') . '" data-toggle="tooltip" target="_blank"  data-sender="'.auth()->guard('doctor')->user()->id.'" data-receiver="'.$row['user_id'].'"><i class="fa fa-phone"></i></a>';
					//chat
					$operation .= ' <a href="'.url('doctor/chat').'" class="btn btn-default d-inline-block chatIniat" title="' . trans('Chat') . '" data-toggle="tooltip" target="_blank" firstname="patient " lastname="'.$row['user_id'].'" data-sender="'.auth()->guard('doctor')->user()->id.'" data-receiver="'.$row['user_id'].'"><i class="fa fa-comments"></i></a>';
                }

                elseif($row['status'] == 3){
                    $operation = ' <a href="report/edit/' . $d .'" class="btn btn-danger d-inline-block" title="' . trans('doctor/report.edit') . '" data-toggle="tooltip"><i class="fa fa-pencil-square-o"></i></a>';
                    $operation .= ' <a href="report/view/' . $d .'" class="btn btn-success d-inline-block" title="' . trans('doctor/report.view') . '" data-toggle="tooltip" target="_blank"><i class="fa fa-eye"></i></a>';
                    // call button
                    $operation .= ' <a href=" ' . $durl .'" class="btn btn-warning d-inline-block callIniat" title="' . trans('doctor/report.call') . '" data-toggle="tooltip" target="_blank"  data-sender="'.auth()->guard('doctor')->user()->id.'" data-receiver="'.$row['user_id'].'"><i class="fa fa-phone"></i></a>';
					//chat
					$operation .= ' <a href="'.url('doctor/chat').'" class="btn btn-default d-inline-block chatIniat" title="' . trans('Chat') . '" data-toggle="tooltip" target="_blank" firstname="patient " lastname="'.$row['user_id'].'" data-sender="'.auth()->guard('doctor')->user()->id.'" data-receiver="'.$row['user_id'].'"><i class="fa fa-comments"></i></a>';
                }
                else{
                    $operation = '';
                }
                    
                return $operation;
            }, 'field' => 'id') 
        );

        $sql_details = array(
            'user' => config('database.connections.mysql.username'),
            'pass' => config('database.connections.mysql.password'),
            'db' => config('database.connections.mysql.database'),
            'host' => config('database.connections.mysql.host')
        );
  
        $joinQuery = '';
        $joinQuery .= " LEFT JOIN users vu ON vu.id = bookings.vender_id";
        $joinQuery .= " LEFT JOIN users pu ON pu.id = bookings.user_id";
        $joinQuery .= " LEFT JOIN service_categories sc ON bookings.service_id = sc.id";
        $joinQuery .= " LEFT JOIN vender_slots vs ON vs.id = bookings.vendor_slot_id";
        $joinQuery .= " LEFT JOIN transactions tr ON tr.booking_id = bookings.id";

        $extraWhere = "bookings.vender_id = ".$userId; //"r.name='doctor'";
        $groupBy = "";//"users.id";

       

        echo json_encode(
                SSP::simple($_GET, $sql_details, $table, $primaryKey, $columns, $joinQuery, $extraWhere, $groupBy)
        );
    }

    /**
     * Function to get all appointments of doctor
     * @param {sender_id,receiver_id}
     * @return JSON
     * @author Durga Parshad
     * @since 12-Febuaray-2020
     */
    public function sendCallNotification(Request $request){
        $dataPush = [
            'sender_id' => $request['sender_id'],
            'receiver_id' => $request['receiver_id'],
            'room' => $request['sender_id'].$request['receiver_id']
        ];
        $title = "Doctor is calling to you.";
        $message = "You will received call from your doctor regarding your appointment.";
        
        //print_r($request['receiver_id']); exit;

        DeviceDetails::sendCallNotification($title ,$message,$request['receiver_id'],$dataPush);
	//print_r($dd);exit;
        $this->response['status'] = 1;
        return response()->json($this->response, 200);
    }
}

website/resources/views/doctor/appointmentreport.blade.php
@extends('doctor.layouts.default')
{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/report.appointment_report') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>{!! trans('admin/report.appointment_report') !!}</h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
            </div>
            <div class="col-xs-12">
                <div class="box">
                    @if(Session::has('message'))
                        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                    @endif
                    {!! Form::open(array('url' => 'doctor/reports/save', 'id' => 'report-form')) !!}
                    <div class="box-body">
                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('name', trans('doctor/report.name')) !!}
                                {!! Form::text('nameread', $username, array('class'=>'form-control','disabled' => 'disabled')) !!}   
                                {!! Form::hidden('booking_id', $booking_id) !!}   
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('gender', trans('doctor/report.gender')) !!}
                                {!! Form::text('genderread', $gender == 1 ? 'Male' : 'Female', array('class'=>'form-control','disabled' => 'disabled')) !!}
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('age', trans('doctor/report.age')) !!}
                                {!! Form::text('age', $age , array('class'=>'form-control','disabled' => 'disabled')) !!}
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('reference_id', trans('doctor/report.reference_id')) !!}
                                {!! Form::text('reference_id', $reference_id , array('class'=>'form-control','disabled' => 'disabled')) !!}
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group has-feedback">
                                {!! Form::label('issue', trans('doctor/report.issue')) !!}
                                {!! Form::text('issue', old('issue'), array('class'=>'form-control')) !!}                       
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group has-feedback">
                                {!! Form::label('report', trans('doctor/report.report')) !!}
                                {!! Form::textarea('report', old('report'), array('class'=>'form-control')) !!}                       
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                <div class="box-footer">
                                    {!! Form::submit(trans('doctor/report.generate'),array('class'=>'btn btn-primary', 'id'=>'submitform')) !!}
                                    <a href="{!! URL::route('listCategory') !!}" class="btn btn-default">{!! trans('admin/common.cancel') !!}</a>
                                </div>
                            </div>
                        </div>
                        {!! Form::close()!!}
                    </div> <!-- /.box -->
                </div> <!-- /.col-xs-12 -->
            </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop
{{-- Scripts --}}

website/resources/views/doctor/banner.blade.php
@extends('admin.layouts.default')

{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/banners.banners') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>{!! trans('admin/banners.banner') !!}</h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
            </div>
            <div class="col-xs-12">
                <div class="box">
                    @if(isset($banner))
                        {!! Form::model($banner, array('route' => array('banners.update', $banner->id), 'method' => 'PATCH', 'id' => 'banner-form', 'files' => true )) !!}
                    @else
                        {!! Form::open(array('route' => 'banners.store', 'id' => 'banner-form', 'files' => true)) !!}
                    @endif
                    <div class="box-body">
                        <div class="form-group has-feedback">
                            {!! Form::label('name', trans('admin/banners.banner_name')) !!}
                            {!! Form::text('name', old('name'), array('class'=>'form-control')) !!}
                            <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                        </div>
                        <div class="form-group has-feedback">
                            {!! Form::label('image', trans('admin/banners.add_image')) !!}
                            <div class=row>
                                <div class="col-md-9">
                                    {!! Form::file('image', array('class'=>'form-control','style'=>'height:auto;')) !!}
                                    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                                </div>
                                <div class="col-md-3">
                                    @if (isset($banner->name))
                                        <img src="{!! URL::asset('/public/banners/'.$banner->image) !!}"  height="50" width="100">
                                    @endif
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        {!! Form::submit(trans('admin/common.submit'),array('class'=>'btn btn-primary', 'id'=>'submitform')) !!}
                        <a href="{!! URL::route('banners.index') !!}" class="btn btn-default">{!! trans('admin/common.cancel') !!}</a>
                    </div>
                    {!! Form::close()!!}
                </div> <!-- /.box -->
            </div> <!-- /.col-xs-12 -->
        </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop
{{-- Scripts --}}
@section('scripts')

@stop

website/resources/views/doctor/editreport.blade.php
@extends('doctor.layouts.default')
{{-- Web site Title --}}
@section('title')
@parent :: {!! trans('admin/report.appointment_report') !!}
@stop
@section('styles')
@stop
{{-- Content --}}
@section('content')
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>{!! trans('admin/report.appointment_report') !!}</h1>
    </section>
    <!-- Main content -->
    <section class="content">
        <!-- Main row -->
        <div class="row">
            <div class="col-md-12">
                <!-- Notifications -->
                @include('admin.includes.notifications')
            </div>
            <div class="col-xs-12">
                <div class="box">
                    @if(Session::has('message'))
                        <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
                    @endif
                    {!! Form::open(array('url' => 'doctor/reports/edit-save', 'id' => 'report-form')) !!}
                    <div class="box-body">
                    <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('name', trans('doctor/report.name')) !!}
                                {!! Form::text('nameread', $name, array('class'=>'form-control','disabled' => 'disabled')) !!}   
                                {!! Form::hidden('booking_id', $booking_id) !!}   
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('gender', trans('doctor/report.gender')) !!}
                                {!! Form::text('genderread', $gender == 1 ? 'Male' : 'Female', array('class'=>'form-control','disabled' => 'disabled')) !!}
                            </div>
                        </div>

                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('age', trans('doctor/report.age')) !!}
                                {!! Form::text('age', $age , array('class'=>'form-control','disabled' => 'disabled')) !!}
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                {!! Form::label('reference_id', trans('doctor/report.reference_id')) !!}
                                {!! Form::text('reference_id', $reference_id , array('class'=>'form-control','disabled' => 'disabled')) !!}
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group has-feedback">
                                {!! Form::label('issue', trans('doctor/report.issue')) !!}
                                {!! Form::text('issue', old('issue') ? old('issue') : $issue, array('class'=>'form-control')) !!}                       
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                        </div>

                        <div class="col-xs-12">
                            <div class="form-group has-feedback">
                                {!! Form::label('report', trans('doctor/report.report')) !!}
                                {!! Form::textarea('report', old('report') ? old('report') : $report, array('class'=>'form-control')) !!}                       
                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                        </div>
                        <div class="col-xs-6">
                            <div class="form-group has-feedback">
                                <div class="box-footer">
                                    {!! Form::submit(trans('doctor/report.generate'),array('class'=>'btn btn-primary', 'id'=>'submitform')) !!}
                                    <a href="{!! URL('doctor/appointments') !!}" class="btn btn-default">{!! trans('admin/common.cancel') !!}</a>
                                </div>
                            </div>
                        </div>
                        {!! Form::close()!!}
                    </div> <!-- /.box -->
                </div> <!-- /.col-xs-12 -->
            </div><!-- /.row (main row) -->

    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@stop
{{-- Scripts --}}
@section('scripts')
<script>
    $('.datepicker').datepicker({
        format: "dd-mm-yyyy",
        //startDate: "od",
        todayHighlight: true,
        todayBtn : true,
        autoclose: true
    }).inputmask('dd-mm-yyyy', {"placeholder": "dd-mm-yyyy", alias: "date", "clearIncomplete": true});
</script>
@stop